# Timing
CONFIG_TIMING_FUNCTIONS=y

# RTT console
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=y

# Increase stack size for benchmarking
CONFIG_MAIN_STACK_SIZE=8192