# Timing
CONFIG_TIMING_FUNCTIONS=y

# RTT console
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=y

# Better crash visibility
CONFIG_ASSERT=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y

# Give the crypto code room
CONFIG_MAIN_STACK_SIZE=8192